# Generated by Django 5.0.6 on 2024-06-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST_Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Goods', 'HSN'), ('Services', 'SAC')], default='Goods', max_length=10)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField(max_length=100)),
                ('rate', models.IntegerField(choices=[('6%', '6'), ('12%', '12'), ('18%', '18'), ('28%', '28')], default='18%')),
            ],
        ),
    ]
