# Generated by Django 5.0.6 on 2024-06-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_gst_classification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GST_Classification',
            new_name='GstClassification',
        ),
        migrations.RenameField(
            model_name='gstclassification',
            old_name='status',
            new_name='type',
        ),
    ]
